export const getSexagenaryCycle = (year) => {
    const sexagenary_cycle = [
        { cn: "甲子", vn: "Giáp Tý" },
        { cn: "乙丑", vn: "Ất Sửu" },
        { cn: "丙寅", vn: "Bính Dần" },
        { cn: "丁卯", vn: "Đinh Mão" },
        { cn: "戊辰", vn: "Mậu Thìn" },
        { cn: "己巳", vn: "Kỷ Tỵ" },
        { cn: "庚午", vn: "Canh Ngọ" },
        { cn: "辛未", vn: "Tân Mùi" },
        { cn: "壬申", vn: "Nhâm Thân" },
        { cn: "癸酉", vn: "Quý Dậu" },
        { cn: "甲戌", vn: "Giáp Tuất" },
        { cn: "乙亥", vn: "Ât Hợi" },
        { cn: "丙子", vn: "Bính Tý" },
        { cn: "丁丑", vn: "Đinh Sửu" },
        { cn: "戊寅", vn: "Mậu Dần" },
        { cn: "己卯", vn: "Kỷ Mão" },
        { cn: "庚辰", vn: "Canh Thìn" },
        { cn: "辛巳", vn: "Tân Tỵ" },
        { cn: "壬午", vn: "Nhâm Ngọ" },
        { cn: "癸未", vn: "Quý Mùi" },
        { cn: "甲申", vn: "Giáp Thân" },
        { cn: "乙酉", vn: "Ất Dậu" },
        { cn: "丙戌", vn: "Bính Tuất" },
        { cn: "丁亥", vn: "Đinh Hợi" },
        { cn: "戊子", vn: "Mậu Tý" },
        { cn: "己丑", vn: "Kỷ Sửu" },
        { cn: "庚寅", vn: "Canh Dần" },
        { cn: "辛卯", vn: "Tân Mão" },
        { cn: "壬辰", vn: "Nhâm Thìn" },
        { cn: "癸巳", vn: "Quý Tỵ" },
        { cn: "甲午", vn: "Giáp Ngọ" },
        { cn: "乙未", vn: "Ất Mùi" },
        { cn: "丙申", vn: "Bính Thân" },
        { cn: "丁酉", vn: "Đinh Dậu" },
        { cn: "戊戌", vn: "Mậu Tuất" },
        { cn: "己亥", vn: "Kỷ Hợi" },
        { cn: "庚子", vn: "Canh Tý" },
        { cn: "辛丑", vn: "Tân Sửu" },
        { cn: "壬寅", vn: "Nhâm Dần" },
        { cn: "癸卯", vn: "Quý Mão" },
        { cn: "甲辰", vn: "Giáp Thìn" },
        { cn: "乙巳", vn: "Ất Tỵ" },
        { cn: "丙午", vn: "Bính Ngọ" },
        { cn: "丁未", vn: "Đinh Mùi" },
        { cn: "戊申", vn: "Mậu Thân" },
        { cn: "己酉", vn: "Kỷ Dậu" },
        { cn: "庚戌", vn: "Canh Tuất" },
        { cn: "辛亥", vn: "Tân Hợi" },
        { cn: "壬子", vn: "Nhâm Tý" },
        { cn: "癸丑", vn: "Quý Sửu" },
        { cn: "甲寅", vn: "Giáp Dần" },
        { cn: "乙卯", vn: "Ất Mão" },
        { cn: "丙辰", vn: "Bính Thìn" },
        { cn: "丁巳", vn: "Đinh Tỵ" },
        { cn: "戊午", vn: "Mậu Ngọ" },
        { cn: "己未", vn: "Kỷ Mùi" },
        { cn: "庚申", vn: "Canh Thân" },
        { cn: "辛酉", vn: "Tân Dậu" },
        { cn: "壬戌", vn: "Nhâm Tuất" },
        { cn: "癸亥", vn: "Quý Hợi" },
    ]

    if (year > 0) {
        return sexagenary_cycle[(year - 3) % 60]
    } else {
        return sexagenary_cycle[(Math.abs(year - 1) + 2) % 60]
    }
}